// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebApplication1.Context;

#nullable disable

namespace WebApplication1.Migrations
{
    [DbContext(typeof(MusicDbContext))]
    [Migration("20240606220920_Modified")]
    partial class Modified
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("WebApplication1.Entities.Album", b =>
                {
                    b.Property<int>("IdAlbum")
                        .HasColumnType("int");

                    b.Property<DateTime>("DataWydania")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<int>("IdWytwornia")
                        .HasColumnType("int");

                    b.Property<string>("NazwaAlbumu")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("IdAlbum")
                        .HasName("Album_pk");

                    b.HasIndex("IdWytwornia");

                    b.ToTable("Album", (string)null);
                });

            modelBuilder.Entity("WebApplication1.Entities.Muzyk", b =>
                {
                    b.Property<int>("IdMuzyk")
                        .HasColumnType("int");

                    b.Property<string>("Imie")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Nazwisko")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<string>("Pseudonim")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("IdMuzyk")
                        .HasName("Muzyk_pk");

                    b.ToTable("Muzyk", (string)null);

                    b.HasData(
                        new
                        {
                            IdMuzyk = 1,
                            Imie = "Yehor",
                            Nazwisko = "Vasylenko",
                            Pseudonim = "ews"
                        },
                        new
                        {
                            IdMuzyk = 2,
                            Imie = "Alex",
                            Nazwisko = "Jaronkiewic",
                            Pseudonim = "awic"
                        },
                        new
                        {
                            IdMuzyk = 3,
                            Imie = "Oliwia",
                            Nazwisko = "Mazur",
                            Pseudonim = "olizur"
                        });
                });

            modelBuilder.Entity("WebApplication1.Entities.Utwor", b =>
                {
                    b.Property<int>("IdUtwor")
                        .HasColumnType("int");

                    b.Property<float>("CzasTrwania")
                        .HasColumnType("real");

                    b.Property<int?>("IdAlbum")
                        .HasColumnType("int");

                    b.Property<string>("NazwaUtworu")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("IdUtwor")
                        .HasName("Utwor_pk");

                    b.HasIndex("IdAlbum");

                    b.ToTable("Utwor", (string)null);

                    b.HasData(
                        new
                        {
                            IdUtwor = 1,
                            CzasTrwania = 999999f,
                            NazwaUtworu = "Pan Tadeusz"
                        },
                        new
                        {
                            IdUtwor = 2,
                            CzasTrwania = 1.5f,
                            NazwaUtworu = "1984"
                        },
                        new
                        {
                            IdUtwor = 3,
                            CzasTrwania = 4f,
                            NazwaUtworu = "Jane Eir"
                        },
                        new
                        {
                            IdUtwor = 4,
                            CzasTrwania = 14.5f,
                            NazwaUtworu = "Harry Potter"
                        },
                        new
                        {
                            IdUtwor = 5,
                            CzasTrwania = 7.8f,
                            NazwaUtworu = "The Ford"
                        },
                        new
                        {
                            IdUtwor = 6,
                            CzasTrwania = 3.4f,
                            NazwaUtworu = "The Return"
                        },
                        new
                        {
                            IdUtwor = 7,
                            CzasTrwania = 2.1f,
                            NazwaUtworu = "Lord of the rings"
                        },
                        new
                        {
                            IdUtwor = 8,
                            CzasTrwania = 2.5f,
                            NazwaUtworu = "Pure and Rich Dad"
                        },
                        new
                        {
                            IdUtwor = 9,
                            CzasTrwania = 7.9f,
                            NazwaUtworu = "Pluca Zlepione Topami"
                        },
                        new
                        {
                            IdUtwor = 10,
                            CzasTrwania = 12.7f,
                            NazwaUtworu = "Wonderfull Day"
                        });
                });

            modelBuilder.Entity("WebApplication1.Entities.WykonawcaUtworu", b =>
                {
                    b.Property<int>("IdMuzyk")
                        .HasColumnType("int");

                    b.Property<int>("IdUtwor")
                        .HasColumnType("int");

                    b.HasKey("IdMuzyk", "IdUtwor")
                        .HasName("WykonawcaUtworu_pk");

                    b.HasIndex("IdUtwor");

                    b.ToTable("WykonawcaUtworu", (string)null);

                    b.HasData(
                        new
                        {
                            IdMuzyk = 1,
                            IdUtwor = 1
                        },
                        new
                        {
                            IdMuzyk = 1,
                            IdUtwor = 2
                        },
                        new
                        {
                            IdMuzyk = 1,
                            IdUtwor = 3
                        },
                        new
                        {
                            IdMuzyk = 1,
                            IdUtwor = 4
                        },
                        new
                        {
                            IdMuzyk = 1,
                            IdUtwor = 5
                        },
                        new
                        {
                            IdMuzyk = 2,
                            IdUtwor = 6
                        },
                        new
                        {
                            IdMuzyk = 2,
                            IdUtwor = 7
                        },
                        new
                        {
                            IdMuzyk = 3,
                            IdUtwor = 8
                        },
                        new
                        {
                            IdMuzyk = 3,
                            IdUtwor = 9
                        },
                        new
                        {
                            IdMuzyk = 3,
                            IdUtwor = 10
                        });
                });

            modelBuilder.Entity("WebApplication1.Entities.Wytwornia", b =>
                {
                    b.Property<int>("IdWytwornia")
                        .HasColumnType("int");

                    b.Property<string>("Nazwa")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("IdWytwornia")
                        .HasName("Wytwornia_pk");

                    b.ToTable("Wytwornia", (string)null);
                });

            modelBuilder.Entity("WebApplication1.Entities.Album", b =>
                {
                    b.HasOne("WebApplication1.Entities.Wytwornia", "Wytwornia")
                        .WithMany("Albums")
                        .HasForeignKey("IdWytwornia")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("Album_Wytwornia");

                    b.Navigation("Wytwornia");
                });

            modelBuilder.Entity("WebApplication1.Entities.Utwor", b =>
                {
                    b.HasOne("WebApplication1.Entities.Album", "Album")
                        .WithMany("Utwors")
                        .HasForeignKey("IdAlbum")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("Utwor_Album");

                    b.Navigation("Album");
                });

            modelBuilder.Entity("WebApplication1.Entities.WykonawcaUtworu", b =>
                {
                    b.HasOne("WebApplication1.Entities.Muzyk", "Muzyk")
                        .WithMany("Utworus")
                        .HasForeignKey("IdMuzyk")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("WykonawcaUtworu_Muzyk");

                    b.HasOne("WebApplication1.Entities.Utwor", "Utwor")
                        .WithMany("Muzyks")
                        .HasForeignKey("IdUtwor")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("WykonawcaUtworu_Utwor");

                    b.Navigation("Muzyk");

                    b.Navigation("Utwor");
                });

            modelBuilder.Entity("WebApplication1.Entities.Album", b =>
                {
                    b.Navigation("Utwors");
                });

            modelBuilder.Entity("WebApplication1.Entities.Muzyk", b =>
                {
                    b.Navigation("Utworus");
                });

            modelBuilder.Entity("WebApplication1.Entities.Utwor", b =>
                {
                    b.Navigation("Muzyks");
                });

            modelBuilder.Entity("WebApplication1.Entities.Wytwornia", b =>
                {
                    b.Navigation("Albums");
                });
#pragma warning restore 612, 618
        }
    }
}
